### PR TITLE
Adding Ps3 Soundlib and Tiny3d scripts

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by zeldin** [comment]
Please note that script 023, 024, 025 already exist on the `develop` branch.
@miigotu What are your plans for the `develop` branch?  Are all new stuff supposed to go there instead, and what are the criteria for when to merge it back to `master`?

**Comment by miigotu** [comment]
develop branch is more of a place for everyone's changes to melt together, and if something gets broken master is still good for anyone who jumps in from the outside. Whenever a feature or major change is verified working and generally non-toxic to master it can be merged over.

Its basically a buffer to avoid mistakes getting into master so easily.

**Comment by miigotu** [comment]
Also, @crystalct for good measure you should keep your master branch even with upstream master (ps3dev's master for whatever repo you are on). Create a separate branch for every pull request that is based on upstream develop, make your pr related changes and PR to develop here.

**Comment by crystalct** [comment]
bitmoji

**Comment by crystalct** [comment]
After solved [this](https://github.com/ps3dev/ps3toolchain/issues/97), i have compiled with success openssl 1.1.1g
Polarssl has become obsolete.... LibCurl stopped to use it since some versions. Can openssl be useful?

**Comment by bucanero** [comment]
> After solved [this](https://github.com/ps3dev/ps3toolchain/issues/97), i have compiled with success openssl 1.1.1g
> Polarssl has become obsolete.... LibCurl stopped to use it since some versions. Can openssl be useful?

yes, an updated/latest openSSL (or mbedTLS) would be nice for sure. I wouldn't remove polarSSL though, because older apps  and libs might still use it.

**Comment by dee12452** [comment]
Yes upvote for openssl for sure! I know some other homebrews have their own port of openssl, it'd be cool to have it be part of ps3libraries by default

**Comment by crystalct** [comment]
Tiring to compile libcairo 1.12.18, i got this error:
```
/tmp/cceFmQ8C.s: Assembler messages:
/tmp/cceFmQ8C.s:64: Error: symbol `.text' is already defined
make[4]: *** [Makefile:5350: cairo_test_suite-partial-clip-text.o] Error 1
```
where is defined (something as) `text` as global? And what is that `text` inside ps3toolchain?

**Comment by zeldin** [comment]
`.text` is the section containing all the code.  It's used internally by gcc/as/ld.  No application code should need to worry about it.
Does the source file you are compile (I assume it would be called `cairo_test_suite-partial-clip-text.c` or so) use any `asm`  directives?  Otherwise this looks like a toolchain bug.

**Comment by crystalct** [comment]
They just defined a function called `text`.
It was just a coincidence.... we cant define a function with that name.

```
#include <stdio.h>

void text () {
	printf("Hello world\n");
}

void main() {
text();
}
```

```
crystal@DESKTOP-2FII39V ~
$ ppu-gcc testgcc.c -o a.exe
/tmp/ccYK5dhF.s: Assembler messages:
/tmp/ccYK5dhF.s:20: Warning: section symbols are already global
/tmp/ccYK5dhF.s:21: Error: symbol `.text' is already defined
```
Or `text` is a reserved word or it's a bug.

**Comment by zeldin** [comment]
No, `text` is not a reserved word.  This works with other PPC64 toolchains, but not with the PPU one, so this is a toolchain bug:
```
hakua:/tmp% powerpc64-unknown-linux-gnu-gcc -o foo foo.c
hakua:/tmp% powerpc64-ps3-elf-gcc -o foo foo.c
/tmp/ccxUiLZW.s: Assembler messages:
/tmp/ccxUiLZW.s:20: Warning: section symbols are already global
/tmp/ccxUiLZW.s:21: Error: symbol `.text' is already defined
hakua:/tmp% 
```
The `powerpc64-unknown-linux-gnu-gcc` compiler uses the name `.L.text` for the non-FD version of the symbol rather than `.text`, which solves the problem.  I don't know why `ppu-gcc` does not do this, but it looks like something that should be fixed, so please open an issue against ps3toolchain.

**Comment by crystalct** [comment]
text is history.. ^_^
Another thing... popen and pclose are present?

```
make[5]: uscita dalla directory «/home/crystal/cairo-1.12.18/build-ppu/boilerplate»
  CCLD   cairo-test-suite
../boilerplate/.libs/libcairoboilerplate.a(cairo-boilerplate.o):(.toc+0x0): undefined reference to `pclose'
../boilerplate/.libs/libcairoboilerplate.a(cairo-boilerplate.o):(.text.cairo_boilerplate_open_any2ppm+0xa8): undefined reference to `popen'
collect2: error: ld returned 1 exit status
```

**Comment by crystalct** [comment]
Done!

**Comment by bucanero** [comment]
@miigotu , can these changes be now added to the `develop` branch, or is something else needed?

**Comment by miigotu** [comment]
Sorry, I've been a little busy (like 500k+ lines changed) on another project

**Comment by crystalct** [comment]
Il gio 30 lug 2020, 06:58 miigotu <notifications@github.com> ha scritto:

**Comment by miigotu** [comment]
lol
image

**Comment by zeldin** [comment]
@miigotu :open_mouth: Are you trying to fix all the bugs in Chrome or something?

**Comment by miigotu** [comment]
Just migration from python2 to python3.8 on SickChill =P it has gone fairly well

**Pull request merged**
