### PR TITLE
Improved downloading of upstreams archives

### PR DESCRIPTION
**Pull request by zeldin**
Ok, this is just an idea.  Kakaroto mentioned that it would be good to be able to build while offline, so I took a stab at improving the archive download process so that it doesn't have to call wget if the file is already downloaded.
A problem with the approach here is that it doesn't currently work for SDL(-libs), since the archive is generated dynamically by github, so it can't be expected to have a predetermined size..

Comments?  Ideas?

### CODE REVIEW

**Comment by zeldin** [comment]
I updated this PR to the current `develop` branch.  The following scripts
```
013-sdl_psl1ght.sh
014-sdl2_psl1ght.sh
015-sdl_psl1ght_libs.sh
022-NoRSX.sh
024-debugnet.sh
```
still use the old system.  All of them are downloading a `tarball/master` from github.  We could change these to use submodules, although that would imply pinning the version, requiring a
```
git submodule update --remote
```
and committing the result every time something should be bumped.  Not saying that is necessarily a bad thing, but it would be a change in behaviour from before.

**Comment by miigotu** [comment]
I think they should be submodules for consistency. We can make workflows that automatically update all of the repos with the correct submodule references on push.

**Comment by zeldin** [comment]
@miigotu This sounds interresting.  I guess for this to work the repo being pushed to needs to be owned by `psdev`, right?  So we should fork these 5 repos?

**Comment by miigotu** [comment]
Yes, if we have patches for them. They don't necessarily need to be under ps3dev, they just need to be somewhere we have write access and can add a deploy key

**Comment by zeldin** [comment]
@miigotu Ok, I think I understand.  So the workflow would live in this project, and the deploy key would allow another project to trigger the workflow, but not to control what it actually does, correct?

**Comment by miigotu** [comment]
Yes it can be done that way through a webhook

**Comment by zeldin** [comment]
Ok, great.  Anyway, I'm merging this PR to `develop` now and we can work out submodules from there.  Hopefully in slightly less than 8 years.  :laughing:

**Pull request merged**
